### ISSUE TITLE
Build weblets

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/builders#26]
repo: [grid_weblets](https://github.com/threefoldtech/grid_weblets)

**Comment by robvanmieghem** [comment]
damned, simple node does not seem enough:
```log

[-] build: + npm install
[-] build: npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[-] build: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[-] build: npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[-] build: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[-] build: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[-] build: npm WARN deprecated micro-base@0.9.0: Switch to @scure/base for audited version of the lib & updates
[-] build: npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[-] build: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[-] build: npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
[-] build: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[-] build: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[-] build: npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[-] build: npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
[-] build: npm ERR! code 1
[-] build: npm ERR! path /app/node_modules/node-sass
[-] build: npm ERR! command failed
[-] build: npm ERR! command sh -c node scripts/build.js
[-] build: npm ERR! Building: /usr/bin/node /app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[-] build: npm ERR! gyp info it worked if it ends with ok
[-] build: npm ERR! gyp verb cli [
[-] build: npm ERR! gyp verb cli   '/usr/bin/node',
[-] build: npm ERR! gyp verb cli   '/app/node_modules/node-gyp/bin/node-gyp.js',
[-] build: npm ERR! gyp verb cli   'rebuild',
[-] build: npm ERR! gyp verb cli   '--verbose',
[-] build: npm ERR! gyp verb cli   '--libsass_ext=',
[-] build: npm ERR! gyp verb cli   '--libsass_cflags=',
[-] build: npm ERR! gyp verb cli   '--libsass_ldflags=',
[-] build: npm ERR! gyp verb cli   '--libsass_library='
[-] build: npm ERR! gyp verb cli ]
[-] build: npm ERR! gyp info using node-gyp@7.1.2
[-] build: npm ERR! gyp info using node@18.13.0 | linux | x64
[-] build: npm ERR! gyp verb command rebuild []
[-] build: npm ERR! gyp verb command clean []
[-] build: npm ERR! gyp verb clean removing "build" directory
[-] build: npm ERR! gyp verb command configure []
[-] build: npm ERR! gyp verb find Python checking Python explicitly set from command line or npm configuration
[-] build: npm ERR! gyp verb find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
[-] build: npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get executable path
[-] build: npm ERR! gyp verb find Python - "/usr/bin/python3" is not in PATH or produced an error
[-] build: npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
[-] build: npm ERR! gyp verb find Python checking if "python3" can be used
[-] build: npm ERR! gyp verb find Python - executing "python3" to get executable path
[-] build: npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
[-] build: npm ERR! gyp verb find Python checking if "python" can be used
[-] build: npm ERR! gyp verb find Python - executing "python" to get executable path
[-] build: npm ERR! gyp verb find Python - "python" is not in PATH or produced an error
[-] build: npm ERR! gyp verb find Python checking if "python2" can be used
[-] build: npm ERR! gyp verb find Python - executing "python2" to get executable path
[-] build: npm ERR! gyp verb find Python - "python2" is not in PATH or produced an error
[-] build: npm ERR! gyp ERR! find Python
[-] build: npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
[-] build: npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
[-] build: npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
[-] build: npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
[-] build: npm ERR! gyp ERR! find Python checking if "python3" can be used
[-] build: npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
[-] build: npm ERR! gyp ERR! find Python checking if "python" can be used
[-] build: npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
[-] build: npm ERR! gyp ERR! find Python checking if "python2" can be used
[-] build: npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
[-] build: npm ERR! gyp ERR! find Python
[-] build: npm ERR! gyp ERR! find Python **********************************************************
[-] build: npm ERR! gyp ERR! find Python You need to install the latest version of Python.
[-] build: npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[-] build: npm ERR! gyp ERR! find Python you can try one of the following options:
[-] build: npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
[-] build: npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
[-] build: npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
[-] build: npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
[-] build: npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
[-] build: npm ERR! gyp ERR! find Python For more information consult the documentation at:
[-] build: npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[-] build: npm ERR! gyp ERR! find Python **********************************************************
[-] build: npm ERR! gyp ERR! find Python
[-] build: npm ERR! gyp ERR! configure error
[-] build: npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
[-] build: npm ERR! gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:302:47)
[-] build: npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:136:21)
[-] build: npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:179:16)
[-] build: npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:266:16)
[-] build: npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
[-] build: npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
[-] build: npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
[-] build: npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
[-] build: npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
[-] build: npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[-] build: npm ERR! gyp ERR! System Linux 5.15.0-1002-kvm
[-] build: npm ERR! gyp ERR! command "/usr/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[-] build: npm ERR! gyp ERR! cwd /app/node_modules/node-sass
[-] build: npm ERR! gyp ERR! node -v v18.13.0
[-] build: npm ERR! gyp ERR! node-gyp -v v7.1.2
[-] build: npm ERR! gyp ERR! not ok
[-] build: npm ERR! Build failed with error code: 1
[-] build:
```

**Comment by robvanmieghem** [comment]
after adding g++, make and Python3:
```log
[-] build: npm ERR! gyp verb download contents checksum {"node-v18.13.0-headers.tar.gz":"50b6f8df7e817f13b1c5efc4223fca2ba40663bb95323ff86b36246be96bc9cd"}
[-] build: npm ERR! gyp verb validating download checksum for node-v18.13.0-headers.tar.gz (50b6f8df7e817f13b1c5efc4223fca2ba40663bb95323ff86b36246be96bc9cd == 50b6f8df7e817f13b1c5efc4223fca2ba40663bb95323ff86b36246be96bc9cd)
[-] build: npm ERR! gyp verb get node dir target node version installed: 18.13.0
[-] build: npm ERR! gyp verb build dir attempting to create "build" dir: /app/node_modules/node-sass/build
[-] build: npm ERR! gyp verb build dir "build" dir needed to be created? /app/node_modules/node-sass/build
[-] build: npm ERR! gyp verb build/config.gypi creating config file
[-] build: npm ERR! gyp verb build/config.gypi writing out config file: /app/node_modules/node-sass/build/config.gypi
[-] build: npm ERR! (node:129) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
[-] build: npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
[-] build: npm ERR! gyp verb config.gypi checking for gypi file: /app/node_modules/node-sass/config.gypi
[-] build: npm ERR! gyp verb common.gypi checking for gypi file: /app/node_modules/node-sass/common.gypi
[-] build: npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
[-] build: npm ERR! gyp info spawn /usr/bin/python3
[-] build: npm ERR! gyp info spawn args [
[-] build: npm ERR! gyp info spawn args   '/app/node_modules/node-gyp/gyp/gyp_main.py',
[-] build: npm ERR! gyp info spawn args   'binding.gyp',
[-] build: npm ERR! gyp info spawn args   '-f',
[-] build: npm ERR! gyp info spawn args   'make',
[-] build: npm ERR! gyp info spawn args   '-I',
[-] build: npm ERR! gyp info spawn args   '/app/node_modules/node-sass/build/config.gypi',
[-] build: npm ERR! gyp info spawn args   '-I',
[-] build: npm ERR! gyp info spawn args   '/app/node_modules/node-gyp/addon.gypi',
[-] build: npm ERR! gyp info spawn args   '-I',
[-] build: npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.13.0/include/node/common.gypi',
[-] build: npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
[-] build: npm ERR! gyp info spawn args   '-Dvisibility=default',
[-] build: npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.13.0',
[-] build: npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/node-gyp',
[-] build: npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.13.0/<(target_arch)/node.lib',
[-] build: npm ERR! gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/node-sass',
[-] build: npm ERR! gyp info spawn args   '-Dnode_engine=v8',
[-] build: npm ERR! gyp info spawn args   '--depth=.',
[-] build: npm ERR! gyp info spawn args   '--no-parallel',
[-] build: npm ERR! gyp info spawn args   '--generator-output',
[-] build: npm ERR! gyp info spawn args   'build',
[-] build: npm ERR! gyp info spawn args   '-Goutput_dir=.'
[-] build: npm ERR! gyp info spawn args ]
[-] build: npm ERR! Traceback (most recent call last):
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
[-] build: npm ERR!     sys.exit(gyp.script_main())
[-] build: npm ERR!              ^^^^^^^^^^^^^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
[-] build: npm ERR!     return main(sys.argv[1:])
[-] build: npm ERR!            ^^^^^^^^^^^^^^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
[-] build: npm ERR!     return gyp_main(args)
[-] build: npm ERR!            ^^^^^^^^^^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
[-] build: npm ERR!     [generator, flat_list, targets, data] = Load(
[-] build: npm ERR!                                             ^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
[-] build: npm ERR!     result = gyp.input.Load(
[-] build: npm ERR!              ^^^^^^^^^^^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
[-] build: npm ERR!     LoadTargetBuildFile(
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
[-] build: npm ERR!     build_file_data = LoadOneBuildFile(
[-] build: npm ERR!                       ^^^^^^^^^^^^^^^^^
[-] build: npm ERR!   File "/app/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
[-] build: npm ERR!     build_file_contents = open(build_file_path, "rU").read()
[-] build: npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[-] build: npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
[-] build: npm ERR! gyp ERR! configure error
[-] build: npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
[-] build: npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/app/node_modules/node-gyp/lib/configure.js:351:16)
[-] build: npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
[-] build: npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[-] build: npm ERR! gyp ERR! System Linux 5.15.0-1002-kvm
[-] build: npm ERR! gyp ERR! command "/usr/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[-] build: npm ERR! gyp ERR! cwd /app/node_modules/node-sass
[-] build: npm ERR! gyp ERR! node -v v18.13.0
[-] build: npm ERR! gyp ERR! node-gyp -v v7.1.2
[-] build: npm ERR! gyp ERR! not ok
```

**Comment by robvanmieghem** [comment]
stupid gyp: File mode U is deprecated in Python 3 https://docs.python.org/3/library/functions.html#open

**Comment by robvanmieghem** [comment]
Question issue in the grid_weblets repo: [Do you need the node-sass dependency? There's already sass](https://github.com/threefoldtech/grid_weblets/issues/1276)

**Comment by robvanmieghem** [comment]
```log
⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠼  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/app/playground/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/playground/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/playground/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/playground/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/playground/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/playground/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /app/playground/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/app/playground/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /app/playground/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/app/playground/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/playground/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/playground/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/playground/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/playground/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/playground/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /app/playground/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/app/playground/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /app/playground/node_modules/cache-loader/dist/index.js:240:7
    at /app/playground/node_modules/neo-async/async.js:2830:7
    at done (/app/playground/node_modules/neo-async/async.js:2865:11)
    at /app/playground/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/app/playground/node_modules/cache-loader/dist/index.js:229:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by robvanmieghem** [comment]
5337193ec6fec0800d6a50ee0b7eb81f111cab95
